version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: ./compose/flask/Dockerfile
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=production
    command: /start
    container_name: api_flask
    restart: unless-stopped

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./compose/nginx/api-flask.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask
    restart: unless-stopped
