#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


/usr/local/bin/gunicorn --worker-class gevent --workers 2 --bind 0.0.0.0:5000 wsgi:app --max-requests 10000 --timeout 5 --keep-alive 5 --log-level info
